### PR TITLE
Freenas/11.0 stable CVE fix

### PR DESCRIPTION
**Pull request by jhixson74**

### CODE REVIEW

**Comment by vaibhav-rbs** [comment]
Jenkins retest this please

**Comment by b-a-t** [comment]
Jenkins, retest this please CLEAN

**Comment by kmoore134** [comment]
jenkins: retest this please

**Comment by b-a-t** [comment]
Changes look good to me, but let's see if Jenkins can build all this cleanly.

**Comment by vaibhav-rbs** [comment]
jenkins: retest this please

**Comment by vaibhav-rbs** [comment]
jenkins: retest this please

**Comment by vaibhav-rbs** [comment]
jenkins: retest this please

**Comment by vaibhav-rbs** [comment]
jenkins: retest this please

**Comment by vaibhav-rbs** [comment]
jenkins: retest this please

**Comment by b-a-t** [comment]
@vaibhav-rbs Jenkins, retest this please CLEAN

**Pull request merged**
