### PR TITLE
Fix for #26039

### PR DESCRIPTION
**Pull request by anodos325**
If the ACL doesn't contain any inherited ACEs, then set DACL_PROTECTED in the security descriptor using smb4acl4_set_control_flags() from source3/modules/nfs4_acls.c. This makes it so that the "Disable Inheritance" button works in Windows Explorer and prevents resulting ACL from auto-inheriting ACL changes in parent directory.

depends on: https://github.com/freenas/ports/pull/67

### CODE REVIEW

**Comment by anodos325** [comment]
Jenkins: retest this please

**Comment by b-a-t** [comment]
Jenkins, retest this please

**Comment by b-a-t** [comment]
Jenkins, retest this please

**Comment by anodos325** [comment]
Jenkins, retest this please

**Pull request merged**
