### PR TITLE
Patch - zfs_disk_free.c

### PR DESCRIPTION
**Pull request by anodos325**
dsize = zpool size if there isn't a quota or refquota on the dataset being shared. 

I believe this fixes problem with inconsistent disk size being displayed in Windows clients as seen in following bug reports:

https://bugs.freenas.org/issues/24737
https://bugs.freenas.org/issues/1481

Reviewer - @b-a-t

### CODE REVIEW

**Review by jhixson74 — COMMENTED** [review]
This looks okay to me with the exception of lines 56-58. Please move this assignment to after the check on lines 54-56.

**Comment by kmoore134** [comment]
John, any comments of the latest state of the patch? Ready to merge?

**Comment by jhixson74** [comment]
On Mon, Jul 17, 2017 at 07:13:36PM -0700, Kris Moore wrote:
>    John, any comments of the latest state of the patch? Ready to merge?

I commented on it in the ticket. I do not agree with patch as is. The
correct way to do this patch is to offer a couple of options to shape
the behavior into what some people might want.

- John
> 
>    —
>    You are receiving this because you commented.
>    Reply to this email directly, view it on GitHub, or mute the thread.
> 
>    Link: https://github.com/freenas/samba/pull/1#issuecomment-315938177

-- 
John Hixson
iXsystems
Enterprise Storage & Servers Driven By Open Source

**Comment by jhixson74** [comment]
See https://bugs.freenas.org/issues/24737 for my comments ;-)

**Pull request closed without merging**
