### PR TITLE
Freenas/11.0 stable cve 11 21 17

### PR DESCRIPTION
**Pull request by jhixson74**

### CODE REVIEW

**Comment by b-a-t** [comment]
This commit https://github.com/freenas/samba/commit/327190893f5f3352a2e6abc4872b54092ee7de68 is part of the leak fix bundle, possibly should be cherry-picked as well.

**Comment by jhixson74** [comment]
That commit doesn't translate 100%, so passed on it.

**Comment by b-a-t** [comment]
LGTM

**Comment by b-a-t** [comment]
Jenkins, retest this please

**Pull request merged**
